[CmdletBinding()]
param([Parameter(Mandatory)][string]$RosterRecordPath,[string]$EvidencePath,[Parameter(Mandatory)][string]$OutputPath)
$ErrorActionPreference='Stop';$r=Get-Content -Raw -LiteralPath $RosterRecordPath|ConvertFrom-Json
if($EvidencePath){$c=Get-Content -Raw -LiteralPath $EvidencePath|ConvertFrom-Json;if($c.input.bic-ne$r.bic){throw 'Evidence BIC does not match roster BIC.'}}
else{$meta={param($reason,$status='DATA_PENDING')[ordered]@{value=$null;status=$status;reason=$reason;source=$null;source_location=$null;raw_answer=$null;evidence_ids=@();checked_at=(Get-Date -Format yyyy-MM-dd);confidence='unknown';human_review_required=$true}}
  $c=[ordered]@{schema_version='2.0.0';case_id=('CDD-'+$r.bic+'-'+(Get-Date -Format yyyyMMdd));review=[ordered]@{type='Periodic Review';frequency='Annual';new_relationship=$false};input=[ordered]@{legal_name=$r.legal_name;bic=$r.bic;iso2=$r.iso2;country=$r.country;country_risk=$r.country_risk;source='approved roster'};acquisition=[ordered]@{accuity_entity_match_attempted=$false;accuity_entity_status='DATA_PENDING';cbddq_availability_checked=$false;cbddq_status='DATA_PENDING';cbddq_read=$false};cbddq_answers=[ordered]@{};fields=[ordered]@{};audit=[ordered]@{factimize_access='UNAVAILABLE';generated_by='CAP-03';validation_level='structural_draft';completion_status='AWAITING_ACCUITY'}}
  $c.fields['basic.legal_name']=[ordered]@{value=$r.legal_name;status='AVAILABLE';reason='Roster value; entity match pending.';source=$r.source.file_name;source_location=('row '+$r.source.row_number);raw_answer=$r.legal_name;evidence_ids=@('EVD-ROSTER-001');checked_at=(Get-Date -Format yyyy-MM-dd);confidence='medium';human_review_required=$true}
  $c.fields['basic.bic']=[ordered]@{value=$r.bic;status='AVAILABLE';reason='Roster value; entity match pending.';source=$r.source.file_name;source_location=('row '+$r.source.row_number);raw_answer=$r.bic;evidence_ids=@('EVD-ROSTER-001');checked_at=(Get-Date -Format yyyy-MM-dd);confidence='medium';human_review_required=$true}
  $c.fields['risk.sanctions_or_watchlist']=&$meta 'Factimize is unavailable and no approved alternative is defined.' 'ACCESS_BLOCKED';$c.fields['risk.pep_hit']=&$meta 'Factimize is unavailable and no approved alternative is defined.' 'ACCESS_BLOCKED'
}
$knowledge=[ordered]@{version='cdd-solution-input-v1';brd_sha256='C8BE6E6333B63F315340280A57A1F7853086241CD9FF686EE28BF0802FC2F08C'};if($c.audit.PSObject.Properties['approved_knowledge']){$c.audit.approved_knowledge=$knowledge}else{$c.audit|Add-Member -NotePropertyName approved_knowledge -NotePropertyValue $knowledge};$parent=Split-Path -Parent $OutputPath;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};[IO.File]::WriteAllText($OutputPath,($c|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)));Write-Output $OutputPath
